Enhavo\Bundle\CalendarBundle\Entity\Appointment:
    type: entity
    table: calendar_appointment
    fields:
        teaser:
            type: string
            length: 255
            nullable: true
        dateFrom:
            type: datetime
            nullable: true
        dateTo:
            type: datetime
            nullable: true
    oneToOne:
        grid:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\GridBundle\Model\GridInterface

    manyToOne:
        picture:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\MediaBundle\Model\FileInterface

    lifecycleCallbacks: {  }
