Enhavo\Bundle\CalendarBundle\Entity\Appointment:
    type: entity
    table: calendar_appointment
    repositoryClass: Enhavo\Bundle\CalendarBundle\Repository\AppointmentRepository
    fields:
        teaser:
            type: text
            nullable: true
        dateFrom:
            type: datetime
            nullable: true
        dateTo:
            type: datetime
            nullable: true
        externalId:
            type: text
            nullable: true
        locationLongitude:
            type: text
            nullable: true
        locationLatitude:
            type: text
            nullable: true
        locationName:
            type: text
            nullable: true
        locationCity:
            type: text
            nullable: true
        locationCountry:
            type: text
            nullable: true
        locationStreet:
            type: text
            nullable: true
        locationZip:
            type: text
            nullable: true
        repeatRule:
            type: text
            nullable: true
        importerName:
            type: text
            nullable: true
        notImporterHandled:
            type: boolean
            nullable: true
    oneToOne:
        container:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\BlockBundle\Model\ContainerInterface

        picture:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\MediaBundle\Model\FileInterface
            orphanRemoval: true

    lifecycleCallbacks: {  }
