Enhavo\Bundle\PageBundle\Entity\Page:
    priority: 5
    index: false
    properties:
        title:
            - Plain:
                weight: 5
                type: title

        teaser:
            - Plain:
                weight: 3
                type: teaser

        content:
            - Collection:
                entity: Enhavo\Bundle\GridBundle\Entity\Content
