services:
    enhavo_calendar_appointment:
        class: '%enhavo_calendar.form.type.appointment.class%'
        arguments:
            - '%enhavo_calendar.model.appointment.class%'
            - '%enhavo_calendar.routing.appointment.strategy%'
            - '%enhavo_calendar.routing.appointment.route%'
            - '%enhavo_translation.translate%'
        tags:
            - { name: form.type }

    validator.appointment_date:
        class:  Enhavo\Bundle\CalendarBundle\Validator\Constraints\AppointmentDateValidator
        arguments:
            - '@service_container'
        tags:
            - { name: validator.constraint_validator, alias: valid_appointment_date }

    enhavo_calendar.extend_listener.appointment:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\CalendarBundle\Entity\Appointment
            - '%enhavo_calendar.model.appointment.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_calendar.menu_builder.calendar:
        class: Enhavo\Bundle\CalendarBundle\Menu\CalendarMenuBuilder
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: calendar }

    enhavo_calendar.import_manager:
        class: Enhavo\Bundle\CalendarBundle\Import\ImportManager
        arguments:
            - '%enhavo_calendar.imports%'
            - '@service_container'

    enhavo_calendar.exporter:
        class: Enhavo\Bundle\CalendarBundle\Export\CalendarExporter
        arguments:
            - '%enhavo_calendar.export_name%'
            - '@doctrine.orm.entity_manager'

    enhavo_calendar.appointment_provider:
        class: Enhavo\Bundle\CalendarBundle\Provider\AppointmentProvider
        arguments:
            - '@doctrine.orm.entity_manager'