services:
    Enhavo\Bundle\CalendarBundle\Form\Type\AppointmentType:
        arguments:
            - '%enhavo_calendar.appointment.model.class%'
            - [default]
        tags:
            - { name: form.type, alias: enhavo_calendar_appointment }

    validator.appointment_date:
        class:  Enhavo\Bundle\CalendarBundle\Validator\Constraints\AppointmentDateValidator
        arguments:
            - '@service_container'
        tags:
            - { name: validator.constraint_validator, alias: valid_appointment_date }

    Enhavo\Bundle\CalendarBundle\Menu\CalendarMenu:
        tags:
            - { name: enhavo_app.menu }

    enhavo_calendar.import_manager:
        class: Enhavo\Bundle\CalendarBundle\Import\ImportManager
        arguments:
            - '%enhavo_calendar.imports%'
            - '@service_container'

    enhavo_calendar.exporter:
        class: Enhavo\Bundle\CalendarBundle\Export\CalendarExporter
        arguments:
            - '%enhavo_calendar.export_name%'
            - '@doctrine.orm.entity_manager'

    enhavo_calendar.appointment_provider:
        class: Enhavo\Bundle\CalendarBundle\Provider\AppointmentProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    Enhavo\Bundle\CalendarBundle\Command\ImportCommand:
        arguments:
            - '@enhavo_calendar.import_manager'
        tags:
            - { name: console.command }

    Enhavo\Bundle\CalendarBundle\Block\CalendarBlockType:
        arguments:
            - '@enhavo_calendar.appointment.repository'
        tags:
            - { name: enhavo_block.block }
