services:
    enhavo_calendar_appointment:
        class: %enhavo_calendar.form.type.appointment.class%
        arguments:
            - %enhavo_calendar.model.appointment.class%
            - %enhavo_calendar.dynamic_routing%
            - %enhavo_calendar.calendar_route%
            - @router
        tags:
            - { name: form.type }