services:
    enhavo_calendar_appointment:
        class: %enhavo_calendar.form.type.appointment.class%
        arguments:
            - %enhavo_calendar.model.appointment.class%
            - %enhavo_calendar.routing.appointment.strategy%
            - %enhavo_calendar.routing.appointment.route%
        tags:
            - { name: form.type }