enhavo_calendar_appointment_index:
    options:
        expose: true
    path: /enhavo/calendar/appointment/index
    methods: [GET]
    defaults:
        _controller: enhavo_calendar.controller.appointment:indexAction
        _sylius:
            viewer:
                title: label.calendar
                translationDomain: EnhavoCalendarBundle

enhavo_calendar_appointment_create:
    options:
        expose: true
    path: /enhavo/calendar/appointment/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_calendar.controller.appointment:createAction
        _sylius:
            viewer:
                translationDomain: EnhavoCalendarBundle
                tabs:
                    main:
                        label: appointment.label.appointment
                        template: EnhavoCalendarBundle:Tab:appointment.html.twig
                    content:
                        label: appointment.label.content
                        template: EnhavoCalendarBundle:Tab:content.html.twig
                    seo:
                        label: appointment.label.seo
                        template: EnhavoCalendarBundle:Tab:seo.html.twig

enhavo_calendar_appointment_update:
    options:
        expose: true
    path: /enhavo/calendar/appointment/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_calendar.controller.appointment:updateAction
        _sylius:
            viewer:
                translationDomain: EnhavoCalendarBundle
                tabs:
                    main:
                        label: appointment.label.appointment
                        template: EnhavoCalendarBundle:Tab:appointment.html.twig
                    content:
                        label: appointment.label.content
                        template: EnhavoCalendarBundle:Tab:content.html.twig
                    seo:
                        label: appointment.label.seo
                        template: EnhavoCalendarBundle:Tab:seo.html.twig

enhavo_calendar_appointment_table:
    options:
        expose: true
    path: /enhavo/calendar/appointment/table
    defaults:
        _controller: enhavo_calendar.controller.appointment:tableAction
        _sylius:
            filters:
                title:
                    type: text
                    property: title
                    label: appointment.label.title
                    translation_domain: EnhavoCalendarBundle
            viewer:
                translationDomain: EnhavoCalendarBundle
                columns:
                    title:
                        type: text
                        label: appointment.label.title
                        property: title
                        width: 7
                    date:
                        type: datetime
                        label: appointment.label.date
                        property: dateFrom
                        width: 5

enhavo_calendar_appointment_delete:
    options:
        expose: true
    path: /enhavo/calendar/appointment/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: enhavo_calendar.controller.appointment:deleteAction

enhavo_calendar_appointment_batch:
    options:
        expose: true
    path: /enhavo/calendar/appointment/batch
    methods: [POST]
    defaults:
        _controller: enhavo_calendar.controller.appointment:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

enhavo_calendar_appointment_preview:
    options:
        expose: true
    path: /enhavo/calendar/appointment/preview
    methods: [POST]
    defaults:
        _controller: enhavo_calendar.controller.appointment:previewAction
