enhavo_calendar_admin_appointment_index:
    path: /appointment/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_calendar_admin_api_appointment_index
        _endpoint:
            type: admin

enhavo_calendar_admin_appointment_create:
    path: /appointment/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_calendar_admin_api_appointment_create
        _endpoint:
            type: admin

enhavo_calendar_admin_appointment_update:
    path: '/appointment/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_calendar_admin_api_appointment_update
        _endpoint:
            type: admin
