enhavo_content:
    sitemap:
        collectors:
            appointment:
                type: publish
                repository: enhavo_calendar.repository.appointment

enhavo_app:
    template_paths:
        enhavo_calendar:
            path: '@EnhavoCalendarBundle/Resources/views'
            priority: 50
    roles:
        enhavo_calendar_appointment_index:
            role: ROLE_ENHAVO_CALENDAR_APPOINTMENT_INDEX
            label: appointment.role.label.index
            translationDomain: EnhavoCalendarBundle
        enhavo_calendar_appointment_create:
            role: ROLE_ENHAVO_CALENDAR_APPOINTMENT_CREATE
            label: appointment.role.label.create
            translationDomain: EnhavoCalendarBundle
        enhavo_calendar_appointment_update:
            role: ROLE_ENHAVO_CALENDAR_APPOINTMENT_UPDATE
            label: appointment.role.label.update
            translationDomain: EnhavoCalendarBundle
        enhavo_calendar_appointment_delete:
            role: ROLE_ENHAVO_CALENDAR_APPOINTMENT_DELETE
            label: appointment.role.label.delete
            translationDomain: EnhavoCalendarBundle

enhavo_calendar:
    importer:

enhavo_routing:
    classes:
        Enhavo\Bundle\CalendarBundle\Entity\Appointment:
            router:
                default:
                    type: slug
                admin:
                    type: id
                    route: enhavo_calendar_appointment_update
            generators:
                slug:
                    type: slug
                    property: title