enhavo_content:
    sitemap:
        collectors:
            appointment:
                type: publish
                repository: enhavo_calendar.repository.appointment

security:
    role_hierarchy:
        ROLE_ADMIN_ENHAVO_CALENDAR_APPOINTMENT_INDEX:
        ROLE_ADMIN_ENHAVO_CALENDAR_APPOINTMENT_UPDATE:
        ROLE_ADMIN_ENHAVO_CALENDAR_APPOINTMENT_CREATE:
        ROLE_ADMIN_ENHAVO_CALENDAR_APPOINTMENT_DELETE: